// Centralized skill logo mapping shared between Skills component and project tech badges.
// Keys must match technology strings used across the site.
export const skillLogos: Record<string, { src?: string; fallback?: string; label?: string }> = {
  'React TS': { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  FastAPI: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg' },
  Docker: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
  'ShadCN UI': { label: 'Shad' },
  'Clerk Auth': { label: 'Clerk' },
  'Google Cloud': { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg' },
  'Chrome Extension': { label: 'Ext' },
  AI: { label: 'AI' },
  Genkit: { label: 'Gen' },
  OCR: { label: 'OCR' },
  'AI Integration': { label: 'AI' },
  'Ant Design UI': { label: 'Ant' },
  'VS Code API': { label: 'VS' },
  'Security Analysis': { label: 'Sec' },
  'Extension Development': { label: 'Ext' },
  Pandas: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg' },
  GeoPandas: { label: 'GeoP' },
  Matplotlib: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matplotlib/matplotlib-original.svg' },
  IPyWidgets: { label: 'IPy' },
  'Data Science': { label: 'DS' },
  GAN: { label: 'GAN' },
  'Computer Vision': { label: 'CV' },
  'Deep Learning': { label: 'DL' },
  'Circuit Design': { label: 'Circ' },
  Arduino: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/arduino/arduino-original.svg' },
  'Wearable Tech': { label: 'Wear' },
  Python: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
  Java: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
  MATLAB: { src: '/icons/matlab.png' },
  HTML: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg' },
  CSS: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg' },
  JavaScript: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
  TypeScript: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
  'C++': { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg' },
  SQL: { src: '/icons/sql.svg' },
  TensorFlow: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg' },
  PyTorch: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg' },
  Django: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg' },
  'React JS/TS': { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  TKinter: { src: '/icons/tkinter.png' },
  Figma: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg' },
  Firebase: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg' },
  Supabase: { src: '/icons/supabase.png' },
  'VS Code': { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg' },
  'GitHub Copilot': { src: '/icons/copilot.png', label: '🤖' },
  PostgreSQL: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
  'Bandsaw Cutting': { src: '/icons/bandsaw.png' },
  Soldering: { src: '/icons/soldering.png' },
  Circuitry: { src: '/icons/circuitry.png' },
  Git: { src: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
  Jupyter: { src: '/icons/jupyter.png' },
  CAD: { src: '/icons/autodesk.svg', label: 'CAD' },
  'Prompt Engineering': { src: '/icons/promptengineering.png' }
};

export const getSkillLogo = (name: string) => skillLogos[name];
